# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccca2e7f9a71d720b538745e067855cd203dbc1212fae07a030af3b5b2b7cc098633221529930c3e0e74765c8225800725d829b0a5d6b8f10bbd1e63967b72aa

test:
  secret_key_base: 578288dc2f2e588dcdea139a4b778395ec1795dd97897aa40f8c1b9dbd976f1ded103167e796bf13d87684facd5b1c5acf967f9047b8a8b7d1e17521a60af22b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
